// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contacts.proto
// Protobuf Java Version: 4.28.0

package com.study.protobuf.entity;

/**
 * Protobuf type {@code com.study.protobuf.entity.PeopleInfo}
 */
public final class PeopleInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.study.protobuf.entity.PeopleInfo)
    PeopleInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      PeopleInfo.class.getName());
  }
  // Use PeopleInfo.newBuilder() to construct.
  private PeopleInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PeopleInfo() {
    name_ = "";
    phoneNumber_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.study.protobuf.entity.Contacts.internal_static_com_study_protobuf_entity_PeopleInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.study.protobuf.entity.Contacts.internal_static_com_study_protobuf_entity_PeopleInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.study.protobuf.entity.PeopleInfo.class, com.study.protobuf.entity.PeopleInfo.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_ = 0;
  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  @java.lang.Override
  public int getAge() {
    return age_;
  }

  public static final int PHONE_NUMBER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.study.protobuf.entity.Phone> phoneNumber_;
  /**
   * <pre>
   * 手机号，字符串List
   * </pre>
   *
   * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.study.protobuf.entity.Phone> getPhoneNumberList() {
    return phoneNumber_;
  }
  /**
   * <pre>
   * 手机号，字符串List
   * </pre>
   *
   * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.study.protobuf.entity.PhoneOrBuilder> 
      getPhoneNumberOrBuilderList() {
    return phoneNumber_;
  }
  /**
   * <pre>
   * 手机号，字符串List
   * </pre>
   *
   * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
   */
  @java.lang.Override
  public int getPhoneNumberCount() {
    return phoneNumber_.size();
  }
  /**
   * <pre>
   * 手机号，字符串List
   * </pre>
   *
   * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
   */
  @java.lang.Override
  public com.study.protobuf.entity.Phone getPhoneNumber(int index) {
    return phoneNumber_.get(index);
  }
  /**
   * <pre>
   * 手机号，字符串List
   * </pre>
   *
   * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
   */
  @java.lang.Override
  public com.study.protobuf.entity.PhoneOrBuilder getPhoneNumberOrBuilder(
      int index) {
    return phoneNumber_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (age_ != 0) {
      output.writeInt32(2, age_);
    }
    for (int i = 0; i < phoneNumber_.size(); i++) {
      output.writeMessage(3, phoneNumber_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, age_);
    }
    for (int i = 0; i < phoneNumber_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, phoneNumber_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.study.protobuf.entity.PeopleInfo)) {
      return super.equals(obj);
    }
    com.study.protobuf.entity.PeopleInfo other = (com.study.protobuf.entity.PeopleInfo) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getAge()
        != other.getAge()) return false;
    if (!getPhoneNumberList()
        .equals(other.getPhoneNumberList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    if (getPhoneNumberCount() > 0) {
      hash = (37 * hash) + PHONE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumberList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.study.protobuf.entity.PeopleInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.study.protobuf.entity.PeopleInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.study.protobuf.entity.PeopleInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.study.protobuf.entity.PeopleInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.study.protobuf.entity.PeopleInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.study.protobuf.entity.PeopleInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.study.protobuf.entity.PeopleInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.study.protobuf.entity.PeopleInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.study.protobuf.entity.PeopleInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.study.protobuf.entity.PeopleInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.study.protobuf.entity.PeopleInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.study.protobuf.entity.PeopleInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.study.protobuf.entity.PeopleInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.study.protobuf.entity.PeopleInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.study.protobuf.entity.PeopleInfo)
      com.study.protobuf.entity.PeopleInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.study.protobuf.entity.Contacts.internal_static_com_study_protobuf_entity_PeopleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.study.protobuf.entity.Contacts.internal_static_com_study_protobuf_entity_PeopleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.study.protobuf.entity.PeopleInfo.class, com.study.protobuf.entity.PeopleInfo.Builder.class);
    }

    // Construct using com.study.protobuf.entity.PeopleInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      age_ = 0;
      if (phoneNumberBuilder_ == null) {
        phoneNumber_ = java.util.Collections.emptyList();
      } else {
        phoneNumber_ = null;
        phoneNumberBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.study.protobuf.entity.Contacts.internal_static_com_study_protobuf_entity_PeopleInfo_descriptor;
    }

    @java.lang.Override
    public com.study.protobuf.entity.PeopleInfo getDefaultInstanceForType() {
      return com.study.protobuf.entity.PeopleInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.study.protobuf.entity.PeopleInfo build() {
      com.study.protobuf.entity.PeopleInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.study.protobuf.entity.PeopleInfo buildPartial() {
      com.study.protobuf.entity.PeopleInfo result = new com.study.protobuf.entity.PeopleInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.study.protobuf.entity.PeopleInfo result) {
      if (phoneNumberBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          phoneNumber_ = java.util.Collections.unmodifiableList(phoneNumber_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.phoneNumber_ = phoneNumber_;
      } else {
        result.phoneNumber_ = phoneNumberBuilder_.build();
      }
    }

    private void buildPartial0(com.study.protobuf.entity.PeopleInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.age_ = age_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.study.protobuf.entity.PeopleInfo) {
        return mergeFrom((com.study.protobuf.entity.PeopleInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.study.protobuf.entity.PeopleInfo other) {
      if (other == com.study.protobuf.entity.PeopleInfo.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (phoneNumberBuilder_ == null) {
        if (!other.phoneNumber_.isEmpty()) {
          if (phoneNumber_.isEmpty()) {
            phoneNumber_ = other.phoneNumber_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePhoneNumberIsMutable();
            phoneNumber_.addAll(other.phoneNumber_);
          }
          onChanged();
        }
      } else {
        if (!other.phoneNumber_.isEmpty()) {
          if (phoneNumberBuilder_.isEmpty()) {
            phoneNumberBuilder_.dispose();
            phoneNumberBuilder_ = null;
            phoneNumber_ = other.phoneNumber_;
            bitField0_ = (bitField0_ & ~0x00000004);
            phoneNumberBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPhoneNumberFieldBuilder() : null;
          } else {
            phoneNumberBuilder_.addAllMessages(other.phoneNumber_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              age_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              com.study.protobuf.entity.Phone m =
                  input.readMessage(
                      com.study.protobuf.entity.Phone.parser(),
                      extensionRegistry);
              if (phoneNumberBuilder_ == null) {
                ensurePhoneNumberIsMutable();
                phoneNumber_.add(m);
              } else {
                phoneNumberBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 2;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {

      age_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      bitField0_ = (bitField0_ & ~0x00000002);
      age_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.study.protobuf.entity.Phone> phoneNumber_ =
      java.util.Collections.emptyList();
    private void ensurePhoneNumberIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        phoneNumber_ = new java.util.ArrayList<com.study.protobuf.entity.Phone>(phoneNumber_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.study.protobuf.entity.Phone, com.study.protobuf.entity.Phone.Builder, com.study.protobuf.entity.PhoneOrBuilder> phoneNumberBuilder_;

    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public java.util.List<com.study.protobuf.entity.Phone> getPhoneNumberList() {
      if (phoneNumberBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phoneNumber_);
      } else {
        return phoneNumberBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public int getPhoneNumberCount() {
      if (phoneNumberBuilder_ == null) {
        return phoneNumber_.size();
      } else {
        return phoneNumberBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public com.study.protobuf.entity.Phone getPhoneNumber(int index) {
      if (phoneNumberBuilder_ == null) {
        return phoneNumber_.get(index);
      } else {
        return phoneNumberBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public Builder setPhoneNumber(
        int index, com.study.protobuf.entity.Phone value) {
      if (phoneNumberBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumberIsMutable();
        phoneNumber_.set(index, value);
        onChanged();
      } else {
        phoneNumberBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public Builder setPhoneNumber(
        int index, com.study.protobuf.entity.Phone.Builder builderForValue) {
      if (phoneNumberBuilder_ == null) {
        ensurePhoneNumberIsMutable();
        phoneNumber_.set(index, builderForValue.build());
        onChanged();
      } else {
        phoneNumberBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public Builder addPhoneNumber(com.study.protobuf.entity.Phone value) {
      if (phoneNumberBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumberIsMutable();
        phoneNumber_.add(value);
        onChanged();
      } else {
        phoneNumberBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public Builder addPhoneNumber(
        int index, com.study.protobuf.entity.Phone value) {
      if (phoneNumberBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumberIsMutable();
        phoneNumber_.add(index, value);
        onChanged();
      } else {
        phoneNumberBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public Builder addPhoneNumber(
        com.study.protobuf.entity.Phone.Builder builderForValue) {
      if (phoneNumberBuilder_ == null) {
        ensurePhoneNumberIsMutable();
        phoneNumber_.add(builderForValue.build());
        onChanged();
      } else {
        phoneNumberBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public Builder addPhoneNumber(
        int index, com.study.protobuf.entity.Phone.Builder builderForValue) {
      if (phoneNumberBuilder_ == null) {
        ensurePhoneNumberIsMutable();
        phoneNumber_.add(index, builderForValue.build());
        onChanged();
      } else {
        phoneNumberBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public Builder addAllPhoneNumber(
        java.lang.Iterable<? extends com.study.protobuf.entity.Phone> values) {
      if (phoneNumberBuilder_ == null) {
        ensurePhoneNumberIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phoneNumber_);
        onChanged();
      } else {
        phoneNumberBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public Builder clearPhoneNumber() {
      if (phoneNumberBuilder_ == null) {
        phoneNumber_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        phoneNumberBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public Builder removePhoneNumber(int index) {
      if (phoneNumberBuilder_ == null) {
        ensurePhoneNumberIsMutable();
        phoneNumber_.remove(index);
        onChanged();
      } else {
        phoneNumberBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public com.study.protobuf.entity.Phone.Builder getPhoneNumberBuilder(
        int index) {
      return getPhoneNumberFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public com.study.protobuf.entity.PhoneOrBuilder getPhoneNumberOrBuilder(
        int index) {
      if (phoneNumberBuilder_ == null) {
        return phoneNumber_.get(index);  } else {
        return phoneNumberBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public java.util.List<? extends com.study.protobuf.entity.PhoneOrBuilder> 
         getPhoneNumberOrBuilderList() {
      if (phoneNumberBuilder_ != null) {
        return phoneNumberBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phoneNumber_);
      }
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public com.study.protobuf.entity.Phone.Builder addPhoneNumberBuilder() {
      return getPhoneNumberFieldBuilder().addBuilder(
          com.study.protobuf.entity.Phone.getDefaultInstance());
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public com.study.protobuf.entity.Phone.Builder addPhoneNumberBuilder(
        int index) {
      return getPhoneNumberFieldBuilder().addBuilder(
          index, com.study.protobuf.entity.Phone.getDefaultInstance());
    }
    /**
     * <pre>
     * 手机号，字符串List
     * </pre>
     *
     * <code>repeated .com.study.protobuf.entity.Phone phone_number = 3;</code>
     */
    public java.util.List<com.study.protobuf.entity.Phone.Builder> 
         getPhoneNumberBuilderList() {
      return getPhoneNumberFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.study.protobuf.entity.Phone, com.study.protobuf.entity.Phone.Builder, com.study.protobuf.entity.PhoneOrBuilder> 
        getPhoneNumberFieldBuilder() {
      if (phoneNumberBuilder_ == null) {
        phoneNumberBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.study.protobuf.entity.Phone, com.study.protobuf.entity.Phone.Builder, com.study.protobuf.entity.PhoneOrBuilder>(
                phoneNumber_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        phoneNumber_ = null;
      }
      return phoneNumberBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.study.protobuf.entity.PeopleInfo)
  }

  // @@protoc_insertion_point(class_scope:com.study.protobuf.entity.PeopleInfo)
  private static final com.study.protobuf.entity.PeopleInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.study.protobuf.entity.PeopleInfo();
  }

  public static com.study.protobuf.entity.PeopleInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PeopleInfo>
      PARSER = new com.google.protobuf.AbstractParser<PeopleInfo>() {
    @java.lang.Override
    public PeopleInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PeopleInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PeopleInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.study.protobuf.entity.PeopleInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

