// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: phone.proto
// Protobuf Java Version: 4.28.0

package com.study.protobuf.entity;

public interface PhoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.study.protobuf.entity.Phone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phone_number = 1;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phone_number = 1;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();
}
